version: "3"

services:

# database service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - proxy

# wordpress Service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - proxy

# nginx service
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
# mounting log dir and and necessary config files to container      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./nginx-logrotate.conf:/etc/logrotate.d/nginx:ro
    depends_on:
      - wordpress
      - db
    networks:
      - proxy
# docker network that containers uses to communicate with each other.
networks:
  proxy:

volumes:
  db_data:
  wordpress_data: